# Generated by Django 5.1.6 on 2025-03-04 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('master_unit_list_id', models.PositiveSmallIntegerField(default=0, unique=True)),
                ('slug', models.CharField(max_length=64, unique=True)),
                ('start', models.PositiveSmallIntegerField(default=0, unique=True)),
                ('end', models.PositiveSmallIntegerField(default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('master_unit_list_id', models.PositiveSmallIntegerField(default=0, unique=True)),
                ('slug', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RulesLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=64, unique=True)),
                ('tonnage', models.PositiveSmallIntegerField(default=0)),
                ('battle_value', models.PositiveSmallIntegerField(default=0)),
                ('cost', models.PositiveBigIntegerField(default=0)),
                ('date_introduced', models.PositiveBigIntegerField(default=0)),
                ('notes', models.TextField(max_length=500)),
                ('point_value', models.PositiveSmallIntegerField(default=0)),
                ('master_unit_list_number', models.PositiveSmallIntegerField(default=0, unique=True)),
                ('era', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='builder.era')),
                ('rules_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='builder.ruleslevel')),
                ('technology', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='builder.technology')),
                ('unit_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='builder.unitrole')),
                ('unit_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='builder.unittype')),
            ],
        ),
    ]
