# Generated by Django 5.1.6 on 2025-03-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='eras',
            field=models.ManyToManyField(to='builder.era'),
        ),
        migrations.AddField(
            model_name='faction',
            name='units',
            field=models.ManyToManyField(to='builder.unit'),
        ),
    ]
